---
--- Generated by Luanalysis
--- Created by pimg.
--- DateTime: 10-02-2023 10:30
---
---

--_G.emmy = {}
--_G.emmy.fixPath = function(path)
--    return string.gsub(path, '/home/pimg/workspace/openresty/hello-world/lib/', '/home/pimg/workspace/openresty/hello-world/lib/')
--end
--
--package.cpath = package.cpath .. ";/usr/local/emmy/?.so"
--local dbg = require('emmy_core')
--dbg.tcpListen('localhost', 9966)
--dbg.waitIDE()
ngx.say("<p>hello, world</p>")